<a href="https://colab.research.google.com/github/bhumi-1830/data_science_lab/blob/main/matrixoperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# a) Create a 3x3 matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

print("3x3 Matrix A:")
print(A)

# Compute determinant
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:", det_A)

# b) Find inverse of the matrix
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("\nInverse of Matrix A:")
    print(inv_A)
else:
    print("\nMatrix is singular, inverse does not exist.")

# c) Solve system of linear equations
# 2x + 3y = 10
# 4x + 5y = 20

B = np.array([[2, 3],
              [4, 5]])

C = np.array([10, 20])

solution = np.linalg.solve(B, C)
print("\nSolution of the system of equations (x, y):")
print(solution)

3x3 Matrix A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant of Matrix A: 0.9999999999999964

Inverse of Matrix A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Solution of the system of equations (x, y):
[5. 0.]
