<a href="https://colab.research.google.com/github/bhumi-1830/data_science_lab/blob/main/MATRIX_PART_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### a) Create a 3x3 square matrix and compute its determinant.

In [1]:
import numpy as np

# Create a 3x3 square matrix
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Matrix A:")
print(matrix_a)

# Compute its determinant
determinant_a = np.linalg.det(matrix_a)

print(f"\nDeterminant of Matrix A: {determinant_a:.2f}")

Original Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix A: 0.00


### b) Find the inverse of the matrix.

In [2]:
import numpy as np

# Let's use a different 3x3 matrix for inverse calculation
# because the previous matrix is singular (determinant is 0 or very close to 0)
matrix_b = np.array([
    [1, 2, 1],
    [4, 5, 2],
    [7, 8, 3]
])

print("Original Matrix B:")
print(matrix_b)

# Compute its determinant to check if it's invertible
determinant_b = np.linalg.det(matrix_b)
print(f"\nDeterminant of Matrix B: {determinant_b:.2f}")

if np.isclose(determinant_b, 0):
    print("\nMatrix B is singular and does not have an inverse.")
else:
    # Find the inverse of the matrix
    inverse_b = np.linalg.inv(matrix_b)
    print("\nInverse of Matrix B:")
    print(inverse_b)

    # Verify the inverse (A * A_inv should be identity matrix)
    identity_check = np.dot(matrix_b, inverse_b)
    print("\nVerification (B * B_inv, should be identity matrix):")
    print(identity_check.round(2)) # Round to handle floating point inaccuracies

Original Matrix B:
[[1 2 1]
 [4 5 2]
 [7 8 3]]

Determinant of Matrix B: 0.00

Matrix B is singular and does not have an inverse.


### c) Solve the following system of linear equations using NumPy:
$2x + 3y = 10$
$4x + 5y = 20$

In [3]:
import numpy as np

# Define the coefficients matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constants vector B
B = np.array([10, 20])

print("Coefficient Matrix A:")
print(A)
print("\nConstants Vector B:")
print(B)

# Solve the system of linear equations using np.linalg.solve
solution = np.linalg.solve(A, B)

print("\nSolution (x, y):")
print(solution)

x = solution[0]
y = solution[1]
print(f"\nTherefore, x = {x:.2f} and y = {y:.2f}")

# Verify the solution
print("\nVerification:")
print(f"2*{x} + 3*{y} = {2*x + 3*y:.2f} (expected 10)")
print(f"4*{x} + 5*{y} = {4*x + 5*y:.2f} (expected 20)")

Coefficient Matrix A:
[[2 3]
 [4 5]]

Constants Vector B:
[10 20]

Solution (x, y):
[5. 0.]

Therefore, x = 5.00 and y = 0.00

Verification:
2*5.0 + 3*0.0 = 10.00 (expected 10)
4*5.0 + 5*0.0 = 20.00 (expected 20)
